"""Shared figure style: SciencePlots base plus the paper's page geometry.

``apply()`` loads the SciencePlots ``science`` style with ``no-latex`` (mathtext instead of a
TeX run, so figure builds do not depend on the local MiKTeX package state), then fixes the
sizes used across the paper: 183 mm double-column width, 8 pt text, 400 dpi raster layers
and TrueType fonts embedded in PDF.
"""
from __future__ import annotations

import matplotlib as mpl
import matplotlib.pyplot as plt
import scienceplots  # noqa: F401  (registers the styles)

WIDTH_IN = 183 / 25.4


def apply() -> None:
    plt.style.use(["science", "no-latex"])
    mpl.rcParams.update({
        "font.size": 8, "axes.labelsize": 8, "axes.titlesize": 8.5, "xtick.labelsize": 7.5, "ytick.labelsize": 7.5,
        "legend.fontsize": 8.5, "figure.dpi": 200, "savefig.dpi": 400, "savefig.bbox": None, "pdf.fonttype": 42,
        "lines.linewidth": 1.2, "axes.linewidth": 0.6,
    })


def write_caption(out, stem: str, label: str, body: str, source: str) -> None:
    """Write the generated caption twice: ``captions/<stem>.tex`` (``\\caption`` + ``\\label``, input by the
    manuscript) and ``captions/<stem>.md`` (review copy). ``body`` is LaTeX; ``source`` stays out of the caption."""
    from pathlib import Path
    caps = Path(out) / "captions"
    caps.mkdir(parents=True, exist_ok=True)
    header = f"generated by scripts from the frozen run; do not edit by hand. Source: {source}"
    (caps / f"{stem}.tex").write_text(f"% {header}\n\\caption{{{body}}}\n\\label{{{label}}}\n", encoding="utf-8")
    import re
    # glossaries acronyms -> plain review text, from the \newacronym definitions of the manuscript
    main = Path(__file__).resolve().parent.parent / "paper2_main.tex"
    if main.is_file():
        acr = {k: (s, l) for k, s, l in re.findall(r"\\newacronym\{(\w+)\}\{([^}]*)\}\{([^}]*)\}",
                                                main.read_text(encoding="utf-8"))}
    else:
        import json
        # The public code release carries only the manuscript's acronym mapping.
        mapping = main.parent / "acronyms.json"
        acr = json.loads(mapping.read_text(encoding="utf-8")) if mapping.is_file() else {}

    def _acr(m):
        short, long = acr.get(m.group(2), (m.group(2), m.group(2)))
        if m.group(1) == "acrshort":
            return short
        long = long[:1].upper() + long[1:] if m.group(1) == "Acrfull" else long
        return f"{long} ({short})"
    md = re.sub(r"\\(acrshort|acrfull|Acrfull)\{(\w+)\}", _acr, body)
    for a, b in (("\\pounds", "£"), ("\\%", "%"), ("$\\times$", "×"), ("\\,", " "), ("~", " "), ("---", "—"), ("--", "–")):
        md = md.replace(a, b)
    (caps / f"{stem}.md").write_text(f"<!-- {header} -->\n{md}\n", encoding="utf-8")


def map_axes(ax) -> None:
    """Map panels: no ticks on any side (SciencePlots turns on top/right and minor ticks)."""
    ax.tick_params(which="both", top=False, right=False, bottom=False, left=False,
                   labelbottom=False, labelleft=False)
    ax.minorticks_off()
