"""Standard figures for the numbered DataOverview display notebooks.

Each ``plot_*`` function returns a ``matplotlib.figure.Figure`` built from
already-landed artifacts; ``save_figure`` writes it under
``results/1_DataOverview/<dir>/figures``.  The notebooks only call and save,
so the figures can be regenerated by code alone.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable, Mapping, Sequence

import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.figure import Figure
from matplotlib.patches import Patch

KIT_GREEN = "#009682"
KIT_BLUE = "#4664AA"
KIT_RED = "#A11035"
KIT_ORANGE = "#DF9B1B"
GREY_5 = "#f2f2f2"
GREY_30 = "#b3b3b3"
GREY_60 = "#666666"

LANDUSE_COLORS = {
    "residential": KIT_BLUE,
    "commercial": KIT_ORANGE,
    "industrial": KIT_RED,
    "agricultural": KIT_GREEN,
    "others": GREY_30,
}
CUZ_COLORS = {"covered": KIT_GREEN, "unknown": KIT_ORANGE, "zero": GREY_30}

_RC = {
    "font.size": 9,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "pdf.fonttype": 42,
    "figure.dpi": 110,
}


def _style() -> None:
    plt.rcParams.update(_RC)


def save_figure(fig: Figure, path: Path | str, *, dpi: int = 170) -> Path:
    """Save ``fig`` as PNG (parents created) and return the path; the figure stays open."""

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(target, dpi=dpi, bbox_inches="tight")
    return target


def _lonlat_axes(ax, title: str) -> None:
    ax.set_xlabel("Longitude [°E]")
    ax.set_ylabel("Latitude [°N]")
    ax.set_title(title)
    ax.set_aspect("equal")


# --------------------------------------------------------------------------
# regions and stations
# --------------------------------------------------------------------------


def plot_regions_and_stations(
    regions: gpd.GeoDataFrame,
    stations: gpd.GeoDataFrame,
    *,
    title: str,
    highlight_column: str | None = None,
    highlight_values: Iterable[str] | None = None,
    highlight_label: str = "analysis regions",
    region_column: str | None = None,
    station_size: float = 0.4,
    figsize: tuple[float, float] = (5.5, 6.5),
) -> Figure:
    """Region polygons (grey) with station points (blue); optional green highlight groups.

    When ``region_column`` is given, only stations assigned to a region (non-null
    in that column) are drawn; the legend states how many were left out.
    """

    _style()
    outside = 0
    if region_column and region_column in stations:
        assigned = stations[region_column].notna()
        outside = int((~assigned).sum())
        stations = stations.loc[assigned]
    fig, ax = plt.subplots(figsize=figsize)
    regions.to_crs("EPSG:4326").plot(ax=ax, color=GREY_5, edgecolor=GREY_30, linewidth=0.4)
    handles = [Patch(facecolor=GREY_5, edgecolor=GREY_30, label="regions")]
    if highlight_column and highlight_values is not None:
        wanted = set(map(str, highlight_values))
        subset = regions.loc[regions[highlight_column].astype(str).isin(wanted)]
        subset.to_crs("EPSG:4326").plot(ax=ax, color=KIT_GREEN, alpha=0.55, edgecolor=GREY_30, linewidth=0.4)
        handles.append(Patch(facecolor=KIT_GREEN, alpha=0.55, label=highlight_label))
    caption = f"{len(regions):,} regions"
    if len(stations):
        stations.to_crs("EPSG:4326").plot(ax=ax, color=KIT_BLUE, markersize=station_size)
        handles.append(plt.Line2D([], [], marker="o", color=KIT_BLUE, linestyle="", markersize=3, label="stations"))
        caption += f", {len(stations):,} stations"
        if outside:
            caption += f" ({outside:,} outside regions omitted)"
    # Legend labels stay at most three words so the box never hides the map;
    # counts go into a second title line instead.
    ax.legend(handles=handles, loc="upper left", frameon=False, fontsize=7)
    _lonlat_axes(ax, f"{title}\n{caption}")
    fig.tight_layout()
    return fig


def plot_group_zoom(
    regions: gpd.GeoDataFrame,
    stations: gpd.GeoDataFrame,
    *,
    group_column: str | None,
    group_value: str,
    label_column: str | None = None,
    region_column: str | None = None,
    max_labels: int = 40,
    figsize: tuple[float, float] = (5.5, 4.5),
) -> Figure:
    """One analysis region with its sub-regions labelled and its stations as points.

    With ``group_column=None`` the whole regions table is one analysis region
    (single-region countries); stations are then filtered by ``region_column``.
    Source-row labels are drawn only when there are at most ``max_labels``.
    """

    _style()
    if group_column:
        region = regions.loc[regions[group_column].astype(str) == str(group_value)]
        points = stations.loc[stations[group_column].astype(str) == str(group_value)] if group_column in stations else stations.iloc[0:0]
    else:
        region = regions
        points = stations.loc[stations[region_column].notna()] if region_column and region_column in stations else stations
    region = region.to_crs("EPSG:4326")
    points = points.to_crs("EPSG:4326")
    fig, ax = plt.subplots(figsize=figsize)
    region.plot(ax=ax, color=GREY_5, edgecolor=GREY_60, linewidth=0.6)
    if len(points):
        points.plot(ax=ax, color=KIT_GREEN, markersize=6)
    if label_column and label_column in region and len(region) <= max_labels:
        for geometry, label in zip(region.geometry, region[label_column].astype(str)):
            centroid = geometry.representative_point()
            ax.annotate(label, (centroid.x, centroid.y), fontsize=6, ha="center", va="center", color=GREY_60)
    _lonlat_axes(ax, f"{group_value}: {len(region)} source rows, {len(points):,} stations")
    fig.tight_layout()
    return fig


# --------------------------------------------------------------------------
# grid
# --------------------------------------------------------------------------


def plot_grid_profile(profile: pd.DataFrame, *, target_points: int, title: str) -> Figure:
    """Side-by-side horizontal bars: projected step length and realised cell count per region."""

    _style()
    labels = profile["region"].astype(str).tolist()
    step = profile["projected_step_m"].to_numpy(dtype=float)
    cells = profile["n_cells"].to_numpy(dtype=float)
    y = np.arange(len(labels))
    fig, (ax_step, ax_count) = plt.subplots(1, 2, figsize=(8.2, 0.32 * len(labels) + 1.6), sharey=True, layout="constrained")
    ax_step.barh(y, step, color=KIT_GREEN, height=0.68)
    ax_step.set_yticks(y, labels)
    ax_step.invert_yaxis()
    ax_step.set_xlabel("Projected grid step [m]")
    ax_step.set_title("Bounded equal-area step")
    ax_step.set_xlim(0, step.max() * 1.15)
    for yi, value in zip(y, step):
        ax_step.text(value + step.max() * 0.01, yi, f"{value:.0f}", va="center", fontsize=7)
    ax_count.barh(y, cells, color=KIT_BLUE, height=0.68)
    ax_count.axvline(target_points, color=KIT_RED, linewidth=0.9, linestyle="--", label=f"target {target_points:,}")
    ax_count.set_xlabel("Grid cells")
    ax_count.set_title("Realised cell count")
    ax_count.set_xlim(0, cells.max() * 1.18)
    ax_count.legend(loc="lower right", frameon=False, fontsize=7)
    for yi, value in zip(y, cells):
        ax_count.text(value + cells.max() * 0.01, yi, f"{value:,.0f}", va="center", fontsize=7)
    fig.suptitle(title)
    return fig


def plot_grid_points(
    grid: gpd.GeoDataFrame,
    *,
    source_key: str,
    region: str,
    outline: gpd.GeoDataFrame | None = None,
    point_size: float = 0.6,
    figsize: tuple[float, float] = (6.0, 5.0),
) -> Figure:
    """Grid cell centroids coloured by their source row, with the region outline."""

    _style()
    frame = grid.to_crs("EPSG:4326")
    keys = frame[source_key].astype(str)
    order = list(dict.fromkeys(keys))
    cmap = plt.get_cmap("tab20", max(len(order), 1))
    fig, ax = plt.subplots(figsize=figsize)
    if outline is not None and len(outline):
        outline.to_crs("EPSG:4326").plot(ax=ax, facecolor="none", edgecolor=GREY_60, linewidth=0.6)
    for index, key in enumerate(order):
        subset = frame.loc[keys == key]
        ax.scatter(subset.geometry.x, subset.geometry.y, s=point_size, color=cmap(index), linewidths=0, label=key)
    if len(order) <= 24:
        ax.legend(loc="center left", bbox_to_anchor=(1.01, 0.5), frameon=False, fontsize=6, markerscale=6, title=source_key)
    _lonlat_axes(ax, f"{region}: {len(frame):,} cells over {len(order)} {source_key} rows")
    fig.tight_layout()
    return fig


# --------------------------------------------------------------------------
# features
# --------------------------------------------------------------------------


def plot_stacked_shares(
    table: pd.DataFrame,
    *,
    index_column: str,
    columns: Sequence[str],
    labels: Sequence[str] | None = None,
    colors: Mapping[str, str] | None = None,
    normalise: bool = True,
    title: str,
    xlabel: str,
) -> Figure:
    """Horizontal stacked bars of ``columns`` per row (shares when ``normalise``)."""

    _style()
    names = table[index_column].astype(str).tolist()
    values = table[list(columns)].to_numpy(dtype=float)
    if normalise:
        totals = values.sum(axis=1, keepdims=True)
        totals[totals == 0] = 1.0
        values = values / totals
    y = np.arange(len(names))
    fig, ax = plt.subplots(figsize=(7.0, 0.32 * len(names) + 1.4))
    left = np.zeros(len(names))
    labels = list(labels) if labels is not None else list(columns)
    for column, label in zip(columns, labels):
        column_values = values[:, list(columns).index(column)]
        color = (colors or {}).get(label) or (colors or {}).get(column)
        ax.barh(y, column_values, left=left, height=0.68, label=label, color=color)
        left = left + column_values
    ax.set_yticks(y, names)
    ax.invert_yaxis()
    ax.set_xlabel(xlabel)
    if normalise:
        ax.set_xlim(0, 1)
    ax.set_title(title)
    ax.legend(loc="center left", bbox_to_anchor=(1.01, 0.5), frameon=False, fontsize=7)
    fig.tight_layout()
    return fig


def plot_cell_values(
    grid: gpd.GeoDataFrame,
    values: np.ndarray,
    *,
    title: str,
    label: str,
    log: bool = False,
    cmap: str = "viridis",
    point_size: float = 0.8,
    figsize: tuple[float, float] = (6.0, 5.0),
) -> Figure:
    """Grid cells coloured by a per-cell value (Built-S fraction, NTL radiance, ...)."""

    _style()
    frame = grid.to_crs("EPSG:4326")
    data = np.asarray(values, dtype=float)
    if log:
        data = np.log10(np.clip(data, 0, None) + 1e-3)
        label = f"log10({label} + 1e-3)"
    fig, ax = plt.subplots(figsize=figsize)
    scatter = ax.scatter(frame.geometry.x, frame.geometry.y, c=data, s=point_size, cmap=cmap, linewidths=0)
    fig.colorbar(scatter, ax=ax, shrink=0.8, label=label)
    _lonlat_axes(ax, title)
    fig.tight_layout()
    return fig


def plot_cell_categories(
    grid: gpd.GeoDataFrame,
    categories: Sequence[str] | np.ndarray,
    *,
    title: str,
    colors: Mapping[str, str],
    order: Sequence[str] | None = None,
    point_size: float = 0.8,
    figsize: tuple[float, float] = (6.0, 5.0),
) -> Figure:
    """Grid cells coloured by a categorical label per cell (dominant land use, C/U/Z class, ...)."""

    _style()
    frame = grid.to_crs("EPSG:4326")
    labels = np.asarray(categories, dtype=str)
    if len(labels) != len(frame):
        raise ValueError(f"categories has {len(labels)} entries for {len(frame)} cells")
    names = list(order) if order is not None else list(dict.fromkeys(labels))
    fig, ax = plt.subplots(figsize=figsize)
    for name in names:
        mask = labels == name
        if not mask.any():
            continue
        ax.scatter(
            frame.geometry.x[mask], frame.geometry.y[mask], s=point_size,
            color=colors.get(name, GREY_60), linewidths=0, label=f"{name} ({int(mask.sum()):,})",
        )
    ax.legend(loc="center left", bbox_to_anchor=(1.01, 0.5), frameon=False, fontsize=7, markerscale=6)
    _lonlat_axes(ax, title)
    fig.tight_layout()
    return fig


def plot_value_histograms(
    series: Mapping[str, np.ndarray],
    *,
    title: str,
    bins: int = 40,
    log_x: bool = False,
) -> Figure:
    """One histogram panel per named value array (shared bins)."""

    _style()
    names = list(series)
    fig, axes = plt.subplots(1, len(names), figsize=(3.6 * len(names), 3.0), squeeze=False)
    for ax, name in zip(axes[0], names):
        data = np.asarray(series[name], dtype=float)
        if log_x:
            data = np.log10(np.clip(data, 0, None) + 1e-3)
        ax.hist(data, bins=bins, color=KIT_BLUE)
        ax.set_title(name, fontsize=8)
        ax.set_ylabel("cells")
        ax.set_xlabel("log10(value + 1e-3)" if log_x else "value")
    fig.suptitle(title, y=1.02)
    fig.tight_layout()
    return fig


__all__ = [
    "CUZ_COLORS",
    "LANDUSE_COLORS",
    "plot_cell_categories",
    "plot_cell_values",
    "plot_grid_points",
    "plot_grid_profile",
    "plot_group_zoom",
    "plot_regions_and_stations",
    "plot_stacked_shares",
    "plot_value_histograms",
    "save_figure",
]
