from __future__ import annotations

import json
from pathlib import Path

from sglib.core.infra.artifacts import atomic_text
from sglib.core.infra.config import load_dataoverview_config, load_toml
from sglib.core.infra.terms import discover_country_profiles


def write_matrix(repo_root: Path | str) -> Path:
    root = Path(repo_root).resolve()
    stage = root / "casestudy" / "1_DataOverview"
    profiles = root / "casestudy" / "config" / "countries"
    general_path = stage / "general" / "general.toml"
    discovered = discover_country_profiles(profiles)
    countries = sorted(
        [
        (code, profile.directory)
        for code, profile in discovered.items()
        if (stage / profile.directory / f"{code}.toml").is_file()
        ],
        key=lambda item: item[1].casefold(),
    )
    categories = list(load_toml(general_path)["categories"]["ids"])
    configurations = {
        code: load_dataoverview_config(
            general_path,
            profiles / f"{code}.toml",
            stage / folder / f"{code}.toml",
        )
        for code, folder in countries
    }
    lines = [
        "<!-- Generated by sglib.dataoverview.overview.matrix; do not edit. -->",
        "",
        "| category | " + " | ".join(code.upper() for code, _ in countries) + " |",
        "|---|" + "---|" * len(countries),
    ]
    for category in categories:
        cells = []
        for code, folder in countries:
            config = configurations[code].values
            datasets = [
                f"{name} ({spec['vintage']}; {spec['license']})"
                for name, spec in config["datasets"].items()
                if spec["category"] == category
            ]
            if category in {"landuse", "built_surface", "features_cuz"} and not datasets:
                datasets = ["shared processing product"]
            scope = config["country"]["evaluation_scope"]
            cells.append(("<br>".join(datasets) or "not applicable") + f"<br>scope={scope}")
        lines.append(f"| {category} | " + " | ".join(cells) + " |")
    output = stage / "general" / "data_matrix.md"
    return atomic_text(output, "\n".join(lines) + "\n")
