schema_version = "sg_experiment_country_v1"
regions = ["NL_FLEVOLAND_0", "NL_FLEVOLAND_1", "NL_FRYSLAN_00", "NL_FRYSLAN_01", "NL_FRYSLAN_10", "NL_FRYSLAN_11", "NL_GELDERLAND_000", "NL_GELDERLAND_001", "NL_GELDERLAND_01", "NL_GELDERLAND_10", "NL_GELDERLAND_11", "NL_NOORD_HOLLAND_00", "NL_NOORD_HOLLAND_01", "NL_NOORD_HOLLAND_10", "NL_NOORD_HOLLAND_11", "NL_ZUID_HOLLAND_R"]
representative_region = "NL_FRYSLAN_01"
t1_regions = []

