# -*- coding: utf-8 -*-
"""
019 - German Börde additive full matrix

Recomputes, for the single Börde region in Germany, the same 21-arm full
matrix used for the UK case (British_weighter_experiments): 3 bases
(Uniform / GPM / GNN) x 7 variants (no correction / multiplicative N/P/NP /
additive N/P/NP). The correction logic is imported directly from the UK
case's shared_correction_utils module (the frozen reference definition), so
the German side only requires two adaptations with zero change to the
numerical semantics:

═══ German adaptations (aliasing only, numerical semantics unchanged) ═══
1. CRS: scu.TARGET_CRS is monkeypatched from 'EPSG:27700' (UK national grid)
   to 'EPSG:25832' (German UTM zone 32N, consistent with the 003/005/009
   pipeline). compute_prox_scores reads the module-level global at call
   time; everything else is left untouched line by line.
2. Column name aliasing: the German region key is 'Name' (Gemeinde),
   aliased to a new 'ITL3' column; the regional demand column
   'Demand (MVA)' is derived using the same formula as 003 (substation
   p_mw summed per Gemeinde). The actual-value column used for evaluation
   is 'p_mw' (German substations), passed in via evaluate_allocation's
   actual_col parameter rather than modifying the function.
3. Voronoi aggregation working_crs = EPSG:3857 (the allocator default, and
   the same value used consistently across 003/005/009), reusing
   scu.compute_voronoi_assignment directly.

═══ Verification discipline: verify against known values before extending
    (same approach as the UK case; new arms are only written to disk once
    all checks pass) ═══
(1) The 8 static arms are checked against the frozen boerde_static_metrics.csv
    from 003 (stored at 4 decimal places -> tolerance 5e-5):
    Uni=voronoi / UniN=voronoi_ntl / UniP=voronoi_prox2 / UniNP=voronoi_prox2_ntl
    / the GPM-family arms use the same mapping with a _gpm suffix. Note that
    003's NP is a sequential stack (ntl -> prox2), while this script applies
    a single renormalization of the combined factor -- the per-region
    renormalization in the multiplicative correction is a projection
    operator, so the two are mathematically identical over the reals, up to
    floating-point noise (~1e-13).
(2) The 4 GNN multiplicative arms are checked per seed against the
    metrics.csv written by 005 (4 decimal places -> tolerance 5e-5):
    GNN=voronoi_GNN / GNNpostN=voronoi_ntl_GNN / GNNpostP=voronoi_prox_GNN /
    GNNpostNP=voronoi_ntl_prox_GNN. This run recomputes the full chain on
    CPU, so there is no GPU re-inference drift.
(3) Same-source cross-check: the multiplicative arms recomputed here from
    gnn_demand are evaluated directly against the corrected demand values
    written to disk by 005 in the pickle (ntl/prox/ntl_prox_gnn_demand),
    with |dev| <= max(1e-9, 1e-6*|ref|).

═══ Uniform x additive structural degeneracy (same behavior as the UK case;
    reported as-is, not a bug) ═══
The German Uniform base is uniform per Gemeinde (the same semantics as
003's 'average_demand'), so within-group base_std = 0 -> alpha = 0 -> the
additive correction is exactly equal to the baseline. This asserts that the
within-group range (ptp) is exactly 0 and that UniAdd* is identical to Uni
(metric-level |dev| <= 1e-9).

Outputs:
    results/de_full_matrix.csv          -- 21 arms x 3 metrics (GNN arms
                                            include per-seed columns + the
                                            seed mean)
    results/de_full_matrix_anchor.json  -- verification report + degeneracy
                                            notes + rule-generated directional
                                            findings

Single sample of 13 substations; no statistical inference is performed
(consistent with the paper's Germany section). Directional findings are
generated by simple numeric comparison rules.
Usage: `python 019_de_additive_full_matrix.py` (cwd = StudyCase/Germany).
"""

import json
import pickle
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
UK_DIR = PROJECT_ROOT / 'StudyCase' / 'British_weighter_experiments'
for p in (str(PROJECT_ROOT), str(UK_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

import shared_correction_utils as scu                      # noqa: E402
from SpatialAllocation.Weighter import weighter_registry   # noqa: E402

# ─── German adaptation 1: CRS monkeypatch (compute_prox_scores reads the module-level global at call time) ───
DE_TARGET_CRS = 'EPSG:25832'
scu.TARGET_CRS = DE_TARGET_CRS

# ════════════════════════════════════════════════════════════
# Paths and constants
# ════════════════════════════════════════════════════════════

DATA_DIR = SCRIPT_DIR / 'results' / 'intermediate'
ASSEMBLED_DIR = DATA_DIR / 'features' / 'assembled'
EXTRACTED_DIR = DATA_DIR / 'features' / 'extracted'
STATIC_CSV = SCRIPT_DIR / 'results' / 'static_allocation' / 'boerde_static_metrics.csv'
MODELS_DIR = SCRIPT_DIR / 'results' / 'models'
OUTPUT_DIR = SCRIPT_DIR / 'results'

RELATION_COL = 'Name'                  # German region key (Gemeinde name)
DEMAND_COL = 'p_mw'                    # Substation actual load column
DERIVED_DEMAND_COL = 'Demand (MVA)'    # Regional demand column (derived using the same formula as 003)

SEEDS = [42, 123, 456]
GNN_CONFIG = 'baseline'                # Training config used for the paper's GNN row
METRICS = ['rmse', 'mae', 'corr']
SIGNALS = ['N', 'P', 'NP']

TOL_FROZEN_4DP = 5e-5 + 1e-9           # 003/005 outputs are stored at 4 decimal places -> half a unit in the last digit
STRONG_REL = 1e-6
STRONG_ABS = 1e-9
TOL_DEGENERATION = 1e-9

# Arm definitions (identical to the UK case)
ARMS = [
    ('Uni',       'uniform', 'none', ''),
    ('UniN',      'uniform', 'mult', 'N'),
    ('UniP',      'uniform', 'mult', 'P'),
    ('UniNP',     'uniform', 'mult', 'NP'),
    ('UniAddN',   'uniform', 'add',  'N'),
    ('UniAddP',   'uniform', 'add',  'P'),
    ('UniAddNP',  'uniform', 'add',  'NP'),
    ('GPM',       'gpm',     'none', ''),
    ('GPMpostN',  'gpm',     'mult', 'N'),
    ('GPMpostP',  'gpm',     'mult', 'P'),
    ('GPMpostNP', 'gpm',     'mult', 'NP'),
    ('GPMaddN',   'gpm',     'add',  'N'),
    ('GPMaddP',   'gpm',     'add',  'P'),
    ('GPMaddNP',  'gpm',     'add',  'NP'),
    ('GNN',       'gnn',     'none', ''),
    ('GNNpostN',  'gnn',     'mult', 'N'),
    ('GNNpostP',  'gnn',     'mult', 'P'),
    ('GNNpostNP', 'gnn',     'mult', 'NP'),
    ('GNNaddN',   'gnn',     'add',  'N'),
    ('GNNaddP',   'gnn',     'add',  'P'),
    ('GNNaddNP',  'gnn',     'add',  'NP'),
]
ARM_META = {label: (base, form, sig) for label, base, form, sig in ARMS}
DEGENERATE_ARMS = ['UniAddN', 'UniAddP', 'UniAddNP']

# (1) Static arms -> frozen row names from 003 (German naming: prox2 = γ=2, consistent with the shared module's PROXIMITY_GAMMA)
FROZEN_ROW_OF = {
    'Uni': 'voronoi',
    'UniN': 'voronoi_ntl',
    'UniP': 'voronoi_prox2',
    'UniNP': 'voronoi_prox2_ntl',
    'GPM': 'voronoi_gpm',
    'GPMpostN': 'voronoi_ntl_gpm',
    'GPMpostP': 'voronoi_prox2_gpm',
    'GPMpostNP': 'voronoi_prox2_ntl_gpm',
}

# (2) GNN multiplicative arms -> per-seed row names from 005's metrics.csv
SEED_ROW_OF = {
    'GNN': 'voronoi_GNN',
    'GNNpostN': 'voronoi_ntl_GNN',
    'GNNpostP': 'voronoi_prox_GNN',
    'GNNpostNP': 'voronoi_ntl_prox_GNN',
}

# (3) Same-source cross-check: keys for the corrected demand values written to the pickle by 005
SAME_SOURCE_KEY_OF = {
    'GNNpostN': 'ntl_gnn_demand',
    'GNNpostP': 'prox_gnn_demand',
    'GNNpostNP': 'ntl_prox_gnn_demand',
}

# Columns for reconstructing the GPM base (same as 003/018, in matching order)
LU_COLS = ['lu_residential_prop', 'lu_commercial_prop', 'lu_industrial_prop',
           'lu_agricultural_prop', 'lu_others_prop']
PCT_COLS = ['residential_percent', 'commercial_percent', 'industrial_percent',
            'agricultural_percent', 'others_percent']


# ════════════════════════════════════════════════════════════
# Data loading and base reconstruction
# ════════════════════════════════════════════════════════════

def load_boerde():
    """Load German data and alias column names (adaptation 2: 'Name' -> new 'ITL3' column, aliasing only)."""
    region_gdf = gpd.read_file(str(DATA_DIR / 'source_regions.gpkg'))
    subs_gdf = gpd.read_file(str(DATA_DIR / 'substations.gpkg'))

    # Derive regional demand using the same formula as 003
    gemeinde_demand = subs_gdf.groupby('Gemeinde')[DEMAND_COL].sum()
    region_gdf[DERIVED_DEMAND_COL] = (
        region_gdf[RELATION_COL].map(gemeinde_demand).fillna(0.0))

    with open(ASSEMBLED_DIR / 'boerde_grid_points.pickle', 'rb') as f:
        grid_gdf, _step = pickle.load(f)

    ntl_npz = np.load(str(EXTRACTED_DIR / 'boerde_ntl.npz'), allow_pickle=True)
    ntl_values = ntl_npz['data'][:, 0]
    assert len(ntl_values) == len(grid_gdf)

    # Sanity assertions: RangeIndex (required by scu's positional-index semantics) + unique region key + full coverage
    assert (grid_gdf.index == np.arange(len(grid_gdf))).all(), \
        'grid_gdf does not have a RangeIndex -- breaks the positional-index semantics relied on by scu'
    assert (subs_gdf.index == np.arange(len(subs_gdf))).all(), \
        'subs_gdf does not have a RangeIndex -- aggregate_by_assignment relies on a RangeIndex'
    assert region_gdf[RELATION_COL].is_unique, 'Gemeinde names are not unique'
    assert set(grid_gdf[RELATION_COL].unique()) <= set(region_gdf[RELATION_COL]), \
        'There are Gemeinden not covered by any region'

    # Alias column (does not overwrite any existing column; 'ITL3' does not exist in the German data)
    assert 'ITL3' not in grid_gdf.columns and 'ITL3' not in region_gdf.columns
    grid_gdf['ITL3'] = grid_gdf[RELATION_COL]
    region_gdf['ITL3'] = region_gdf[RELATION_COL]

    return grid_gdf, region_gdf, subs_gdf, ntl_values


def compute_uniform_base(grid_gdf, region_sub):
    """Uniform base: uniform per Gemeinde (same semantics as 003's 'average_demand', using the same formula as the UK case)."""
    region_info = region_sub.set_index('ITL3')
    base = np.zeros(len(grid_gdf))
    for key, group in grid_gdf.groupby('ITL3'):
        if key not in region_info.index:
            continue
        total = region_info.loc[key, DERIVED_DEMAND_COL]
        base[group.index] = total / len(group)
    return base


def compute_gpm_base(grid_gdf, region_sub, subs_gdf):
    """GPM base: row-by-row reconstruction of 003's 'landuse_demand' (categorical GPM -> normalized per Gemeinde)."""
    gpm = weighter_registry.create(
        'gpm', config={'mode': 'categorical', 'proportion_columns': LU_COLS})
    gpm_res = gpm.compute(grid_gdf, target_gdf=subs_gdf)
    W = gpm_res.weights

    region_info = region_sub.set_index('ITL3')
    base = np.zeros(len(grid_gdf))
    n_fallback = 0
    for key, group in grid_gdf.groupby('ITL3'):
        if key not in region_info.index:
            continue
        total = region_info.loc[key, DERIVED_DEMAND_COL]
        idx = group.index
        pcts = np.array([region_info.loc[key, c] for c in PCT_COLS])
        score = W[idx] @ pcts
        s = score.sum()
        if s > 0:
            base[idx] = total * score / s
        else:
            base[idx] = total / len(group)
            n_fallback += 1
    return base, n_fallback


# ════════════════════════════════════════════════════════════
# Main pipeline
# ════════════════════════════════════════════════════════════

def main():
    print('=' * 70)
    print('German Börde additive full matrix (019)')
    print('=' * 70)

    grid_gdf, region_gdf, subs_gdf, ntl_values = load_boerde()
    n_subs = len(subs_gdf)
    print(f'Gemeinden: {grid_gdf["ITL3"].nunique()} | Substations: {n_subs} '
          f'| Grid points: {len(grid_gdf)} | prox CRS: {scu.TARGET_CRS}')

    # Factors (frozen definition from scu; γ=2.0 = scu.PROXIMITY_GAMMA, same as the 005 post-correction)
    prox_scores = scu.compute_prox_scores(grid_gdf, subs_gdf)
    ntl_factor, prox_factor = scu.compute_factors(grid_gdf, ntl_values, prox_scores)
    factors = {'N': ntl_factor, 'P': prox_factor, 'NP': ntl_factor * prox_factor}

    # Voronoi assignment (allocator default working_crs=3857, solved once and shared across the pipeline)
    assignment = scu.compute_voronoi_assignment(grid_gdf, subs_gdf)

    def eval_demand(demand_arr):
        subs_result = scu.aggregate_by_assignment(subs_gdf, assignment, demand_arr)
        return scu.evaluate_allocation(subs_result, actual_col=DEMAND_COL)

    def seven_variants(base_demand):
        out = {('none', ''): eval_demand(base_demand)}
        for sig in SIGNALS:
            mult = scu.apply_standard_multiplicative(
                base_demand, factors[sig], grid_gdf, region_gdf)
            out[('mult', sig)] = eval_demand(mult)
            add = scu.apply_additive_correction(
                base_demand, factors[sig], grid_gdf, region_gdf)
            out[('add', sig)] = eval_demand(add)
        return out

    # ── 1. Static bases ──
    uni_base = compute_uniform_base(grid_gdf, region_gdf)
    gpm_base, n_fb = compute_gpm_base(grid_gdf, region_gdf, subs_gdf)

    # Degeneracy precondition: values within each Uniform-base group are exactly equal
    uni_ptp_max = 0.0
    for _key, group in grid_gdf.groupby('ITL3'):
        g = uni_base[group.index]
        if len(g):
            uni_ptp_max = max(uni_ptp_max, float(g.max() - g.min()))
    assert uni_ptp_max == 0.0, \
        f'Uniform base within-group ptp={uni_ptp_max} != 0 -- degeneracy precondition violated'

    # values[label][metric] = scalar (GNN arms = seed mean); per-seed values stored separately
    values = {label: {} for label, *_ in ARMS}
    per_seed = {label: {s: {} for s in SEEDS}
                for label, base, *_ in ARMS if base == 'gnn'}
    same_source_ref = {label: {s: {} for s in SEEDS} for label in SAME_SOURCE_KEY_OF}

    for base_name, base_arr in (('uniform', uni_base), ('gpm', gpm_base)):
        variants = seven_variants(base_arr)
        for label, base, form, sig in ARMS:
            if base != base_name:
                continue
            for m in METRICS:
                values[label][m] = variants[(form, sig)][m]

    # ── 2. GNN base (baseline config x 3 seeds) ──
    for seed in SEEDS:
        gd_path = (MODELS_DIR / GNN_CONFIG / f'seed_{seed}'
                   / 'grid_demands' / 'boerde_grid_demands.pickle')
        with open(gd_path, 'rb') as f:
            grid_demands = pickle.load(f)
        for key in ['gnn_demand'] + list(SAME_SOURCE_KEY_OF.values()):
            assert key in grid_demands, f'seed {seed}: grid_demands is missing {key}'
        gnn_base = np.asarray(grid_demands['gnn_demand'], dtype=float)
        assert len(gnn_base) == len(grid_gdf)

        variants = seven_variants(gnn_base)
        for label, base, form, sig in ARMS:
            if base != 'gnn':
                continue
            for m in METRICS:
                per_seed[label][seed][m] = variants[(form, sig)][m]

        # Same-source cross-check reference: direct evaluation of the corrected demand written to disk by 005
        for label, key in SAME_SOURCE_KEY_OF.items():
            ref_metrics = eval_demand(np.asarray(grid_demands[key], dtype=float))
            for m in METRICS:
                same_source_ref[label][seed][m] = ref_metrics[m]

    for label, base, form, sig in ARMS:
        if base != 'gnn':
            continue
        for m in METRICS:
            values[label][m] = float(np.mean(
                [per_seed[label][s][m] for s in SEEDS]))

    # ── 3. Verification checks (only written to disk if all pass) ──
    print('\n──── Verification checks (verify against known values before extending) ────')
    anchors = {'frozen_static': {}, 'gnn_per_seed': {}, 'same_source_gnn': {}}

    frozen = pd.read_csv(STATIC_CSV, index_col=0)
    for label, row in FROZEN_ROW_OF.items():
        for m in METRICS:
            ref = float(frozen.loc[row, m])
            dev = abs(values[label][m] - ref)
            anchors['frozen_static'][f'{label}_{m}'] = {
                'recomputed': values[label][m], 'ref': ref,
                'abs_dev': dev, 'tol': TOL_FROZEN_4DP,
                'passed': bool(dev <= TOL_FROZEN_4DP)}

    seed_csv = {s: pd.read_csv(MODELS_DIR / GNN_CONFIG / f'seed_{s}' / 'metrics.csv',
                               index_col=0) for s in SEEDS}
    for label, row in SEED_ROW_OF.items():
        for m in METRICS:
            max_dev = 0.0
            for s in SEEDS:
                ref = float(seed_csv[s].loc[row, m])
                max_dev = max(max_dev, abs(per_seed[label][s][m] - ref))
            anchors['gnn_per_seed'][f'{label}_{m}'] = {
                'max_abs_dev': max_dev, 'tol': TOL_FROZEN_4DP,
                'passed': bool(max_dev <= TOL_FROZEN_4DP)}

    for label in SAME_SOURCE_KEY_OF:
        for m in METRICS:
            max_dev, max_rel = 0.0, 0.0
            ok = True
            for s in SEEDS:
                got = per_seed[label][s][m]
                ref = same_source_ref[label][s][m]
                dev = abs(got - ref)
                tol = max(STRONG_ABS, STRONG_REL * abs(ref))
                ok = ok and (dev <= tol)
                max_dev = max(max_dev, dev)
                max_rel = max(max_rel, dev / max(abs(ref), 1e-12))
            anchors['same_source_gnn'][f'{label}_{m}'] = {
                'max_abs_dev': max_dev, 'max_rel_dev': max_rel, 'passed': bool(ok)}

    failed = [f'{cat}/{k}' for cat in anchors for k, e in anchors[cat].items()
              if not e['passed']]
    n_checks = sum(len(anchors[c]) for c in anchors)
    if failed:
        raise RuntimeError(f'{len(failed)}/{n_checks} verification checks failed: {failed} -- '
                           f'new-arm outputs are not written until all checks pass')
    print(f'  All {n_checks} verification checks passed (frozen_static {len(anchors["frozen_static"])} | '
          f'gnn_per_seed {len(anchors["gnn_per_seed"])} | '
          f'same_source {len(anchors["same_source_gnn"])})')

    # ── 4. Uniform x additive degeneracy verification ──
    deg_max = 0.0
    deg_detail = {}
    for label in DEGENERATE_ARMS:
        for m in METRICS:
            dev = abs(values[label][m] - values['Uni'][m])
            deg_detail[f'{label}_{m}'] = dev
            deg_max = max(deg_max, dev)
    if deg_max > TOL_DEGENERATION:
        raise RuntimeError(f'UniAdd degeneracy deviation {deg_max:.3e} exceeds tolerance '
                           f'{TOL_DEGENERATION} -- inconsistent with the structural derivation')
    print(f'  Degeneracy check: UniAdd* is identical to Uni, max metric-level deviation {deg_max:.3e}')

    # ── 5. Write the full matrix to disk ──
    rows = []
    for label, base, form, sig in ARMS:
        for m in METRICS:
            row = {
                'arm': label, 'base': base, 'form': form, 'signal': sig,
                'metric': m,
                'structural_degeneration': label in DEGENERATE_ARMS,
                'n_seeds': len(SEEDS) if base == 'gnn' else 0,
                'value': values[label][m],
            }
            if base == 'gnn':
                vs = np.array([per_seed[label][s][m] for s in SEEDS])
                for s in SEEDS:
                    row[f'value_seed_{s}'] = per_seed[label][s][m]
                row['std_ddof0_seeds'] = float(vs.std())
            else:
                for s in SEEDS:
                    row[f'value_seed_{s}'] = None
                row['std_ddof0_seeds'] = None
            rows.append(row)
    full_matrix = pd.DataFrame(rows)
    full_matrix.to_csv(OUTPUT_DIR / 'de_full_matrix.csv', index=False)
    print(f'  de_full_matrix: {len(full_matrix)} rows (21 arms × 3 metrics)')

    # ── 6. Directional findings (generated by numeric rules; no inference for the 13-substation single sample) ──
    def rmse(label):
        return values[label]['rmse']

    def rel(a, b):
        return (rmse(a) - rmse(b)) / rmse(b)

    def better_or_worse(a, b):
        return 'improves' if rmse(a) < rmse(b) else 'worsens'

    directional = {
        'note': 'Qualitative direction only for the single sample (13 substations); no statistical inference (consistent with the tab:germany reporting convention used in the paper)',
        'additive_vs_baseline_gnn': {
            f'GNNadd{sig} vs GNN': {
                'rmse_a': rmse(f'GNNadd{sig}'), 'rmse_b': rmse('GNN'),
                'rel_change': rel(f'GNNadd{sig}', 'GNN'),
                'direction': better_or_worse(f'GNNadd{sig}', 'GNN')}
            for sig in SIGNALS},
        'additive_vs_multiplicative_gnn': {
            f'GNNadd{sig} vs GNNpost{sig}': {
                'rmse_a': rmse(f'GNNadd{sig}'), 'rmse_b': rmse(f'GNNpost{sig}'),
                'rel_change': rel(f'GNNadd{sig}', f'GNNpost{sig}'),
                'direction': better_or_worse(f'GNNadd{sig}', f'GNNpost{sig}')}
            for sig in SIGNALS},
        'additive_vs_baseline_gpm': {
            f'GPMadd{sig} vs GPM': {
                'rmse_a': rmse(f'GPMadd{sig}'), 'rmse_b': rmse('GPM'),
                'rel_change': rel(f'GPMadd{sig}', 'GPM'),
                'direction': better_or_worse(f'GPMadd{sig}', 'GPM')}
            for sig in SIGNALS},
        'additive_vs_multiplicative_gpm': {
            f'GPMadd{sig} vs GPMpost{sig}': {
                'rmse_a': rmse(f'GPMadd{sig}'), 'rmse_b': rmse(f'GPMpost{sig}'),
                'rel_change': rel(f'GPMadd{sig}', f'GPMpost{sig}'),
                'direction': better_or_worse(f'GPMadd{sig}', f'GPMpost{sig}')}
            for sig in SIGNALS},
        'headline_best_additive_gnn_vs_best_static': {
            'best_additive_gnn': min(
                (f'GNNadd{sig}' for sig in SIGNALS), key=rmse),
            'best_static_arm': min(
                (lbl for lbl, b, f_, s_ in ARMS if b != 'gnn'
                 and lbl not in DEGENERATE_ARMS), key=rmse),
        },
    }
    hb = directional['headline_best_additive_gnn_vs_best_static']
    hb['rmse_best_additive_gnn'] = rmse(hb['best_additive_gnn'])
    hb['rmse_best_static'] = rmse(hb['best_static_arm'])

    # ── 7. Write the verification report to disk ──
    report = {
        'meta': {
            'script': '019_de_additive_full_matrix.py',
            'purpose': 'German Börde additive full matrix (same definition as the UK case)',
            'generated_at': datetime.now(timezone.utc).isoformat(),
            'gnn_config': GNN_CONFIG, 'seeds': SEEDS,
            'prox_crs': DE_TARGET_CRS,
            'adaptation': ['scu.TARGET_CRS -> EPSG:25832 (monkeypatch, read from the module global at call time)',
                           "Region key 'Name' aliased to a new 'ITL3' column (zero change to numerical semantics)",
                           "Evaluation actual_col='p_mw' (passed as a parameter, not a function change)"],
            'gpm_fallback_groups': n_fb,
            'mult_np_note': ('The multiplicative NP variant in this script applies a single '
                             'renormalization of the combined factor; 003/005 instead apply a '
                             'sequential stack (ntl -> prox2). The per-region renormalization in '
                             'the multiplicative correction is a projection operator, so the two '
                             'are mathematically identical over the reals (numerically confirmed '
                             'by verification checks (1) and (2)).'),
        },
        'anchor_summary': {'n_checks': n_checks, 'n_failed': 0,
                           'policy': 'Verify against known values before extending: any failed check raises an error and no new-arm outputs are written'},
        'anchors': anchors,
        'uniform_additive_degeneration': {
            'structural_degeneration': True,
            'affected_arms': DEGENERATE_ARMS,
            'uniform_base_within_group_ptp_max': uni_ptp_max,
            'metric_level_max_abs_dev': deg_detail,
            'tol': TOL_DEGENERATION,
            'reason': ('The additive alpha = base_std / offset_std is supplied by the base '
                       'itself; the German Uniform base has within-group base_std = 0 per '
                       'Gemeinde, so alpha = 0 and the correction is exactly equal to the '
                       'baseline (the same structural degeneracy seen in the UK case, not a bug)'),
        },
        'directional_findings': directional,
    }
    with open(OUTPUT_DIR / 'de_full_matrix_anchor.json', 'w', encoding='utf-8') as f:
        json.dump(report, f, ensure_ascii=False, indent=2)

    # ── 8. Console summary ──
    print('\n──── Full matrix RMSE (single Börde region; GNN arms = mean ± ddof0 std across 3 seeds) ────')
    for label, base, form, sig in ARMS:
        if base == 'gnn':
            vs = np.array([per_seed[label][s]['rmse'] for s in SEEDS])
            extra = f' ± {vs.std():.4f}'
        else:
            extra = ''
        deg = '  [structural degeneracy = Uni]' if label in DEGENERATE_ARMS else ''
        print(f'  {label:10s} {values[label]["rmse"]:8.4f}{extra}{deg}')

    print('\n──── Directional findings (additive vs multiplicative, GNN base) ────')
    for k, v in directional['additive_vs_multiplicative_gnn'].items():
        print(f"  {k}: {v['rmse_a']:.4f} vs {v['rmse_b']:.4f} "
              f"({v['rel_change']:+.1%}, {v['direction']})")
    print(f'\nOutput: {OUTPUT_DIR / "de_full_matrix.csv"}')
    print('019 complete.')


if __name__ == '__main__':
    main()
