# -*- coding: utf-8 -*-
"""021 - German Börde phase-diagram points (completing the three-country flagship phase diagram).

Background: the phase-diagram points for the UK (240 points) and Australia
(180 points) cases have already been merged into
uk_au_phase_points_merged.csv (420 rows, with a hook left for a German
addition). This step computes the German case's phase-diagram points to
complete the three-country flagship phase diagram: the UK's GNN x
multiplicative points fall on the hurt side, Australia's fall on the help
side -- Germany's GNN x multiplicative points are expected to also fall on
the hurt side (019 measured GNNpostN worsening by +64% and GNNpostNP by
+193%). If the theoretical prediction agrees with the observed sign in all
three cases, then the three countries are three points on the **same
theoretical line**.

═══ Definitions (identical to the UK and Australia cases) ═══
- Per substation:
    rho_j = (d_true_j + eps) / (d_base_j + eps)   -- residual ratio
    F_j = (d_corr_j + eps) / (d_base_j + eps)     -- effective correction factor
  eps = total regional demand x 1e-6 (protects against log(0); the count of
  protected samples is recorded in the output).
- Alignment rho = Pearson corr(log F, log rho_resid); sigma_r = std(log
  rho_resid), sigma_c = std(log F) (numpy population standard deviation,
  ddof=0).
- Delta RMSE = RMSE(corrected) - RMSE(base), where RMSE is computed on the
  **raw** (not eps-protected) allocation values via scu.evaluate_allocation
  (actual_col='p_mw', the same convention as the German 003/019 scripts).
- Theoretical prediction predicted_help <=> rho > sigma_c/(2*sigma_r);
  observed actual_help <=> delta RMSE < 0.

═══ Combination space (Germany = single Börde region, 13 substations) ═══
Base in {Uniform, GPM, GNN x 3 seeds (baseline config)} x signal in
{N, P, NP} (multiplicative apply_standard_multiplicative) -> 1 x 3 x
(2 + 3) = 15 rows.
n = 13 substations -- the sample size for estimating rho is small; this is
reported as-is (a small-sample case worth flagging explicitly), with no
statistical inference performed (consistent with the paper's Germany
section).

═══ Implementation path (reused directly from 019, zero change to numerical
    semantics) ═══
The correction-factor construction and Voronoi aggregation are reused by
importing the 019 module: CRS monkeypatch (EPSG:25832), 'Name' -> 'ITL3'
column alias, and the same load_boerde / compute_uniform_base /
compute_gpm_base functions and frozen scu formulas.

═══ Built-in verification checks (guard against drift in the base/correction
    pipeline; same approach as the Australia case, plus a dual anchor
    against 019) ═══
(1) 4-decimal-place frozen anchor: the 8 static arms are checked against
    003's boerde_static_metrics.csv, and the 4 GNN arms are checked per
    seed against 005's metrics.csv (stored at 4 decimal places -> tolerance
    5e-5 + 1e-9, same as 019).
(2) Full-precision pipeline anchor: all 20 RMSE values (bases + corrected
    arms x seeds) are checked against 019's de_full_matrix.csv (stored at
    full precision, deterministic on the same CPU pipeline -> tolerance
    1e-9).
Any failed check raises an error immediately (an incorrect base invalidates
everything downstream).

═══ Three-country merge (the paper's complete flagship phase-diagram data) ═══
Reads Australia's uk_au_phase_points_merged.csv (UK 240 + AU 180, transcribed
without recomputation, read-only) and appends the 15 DE rows to produce
three_country_phase_points.csv (435 rows).

═══ Deviations from the UK/AU conventions (recorded in summary.deviations) ═══
1. Single region, single fold: the GNN base is 005's
   grid_demands['gnn_demand'] (baseline config), i.e. the training region's
   own prediction (Germany has no k-fold test fold) -- fold='-', which
   differs from the UK/AU test-fold convention and is reported as such.
2. Demand convention = p_mw (MW); the regional demand 'Demand (MVA)' is
   derived by summing substation p_mw per Gemeinde (same formula as 003) --
   d_true and the total regional demand share the same source (whereas
   UK/AU use independent statistical sources).
3. The CRS/aliasing adaptation reuses 019 (EPSG:25832 monkeypatch, Voronoi
   working_crs=3857).
4. n=13 substations, single region: the sampling error on rho is large
   (Fisher z SE = 1/sqrt(n-3) ~= 0.316); the sample size is recorded
   numerically in summary.small_sample_registration.

All verdict fields are generated by numeric rules rather than entered by
hand; the verdict thresholds match the UK case: value >= 0.9 -> supported;
>= 0.5 -> partially_supported; otherwise not_supported.
This step has no source of randomness (deterministic post-processing); runs
entirely on CPU (capped at 4 threads). All upstream frozen artifacts are
treated as read-only.

Outputs:
    results/de_phase_points.csv              -- 15 phase-diagram points
        (schema = country + the same 18 columns as the UK case, aligned
        column-for-column with the merged data)
    results/three_country_phase_points.csv   -- 435-point three-country merge
        (UK 240 + AU 180 + DE 15; the paper's complete flagship phase-diagram
        data)
    results/de_phase_summary.json            -- confusion matrix + DE
        placement verification + consistency with the +64%/+193% observed
        worsening + three-country merged accuracy + small-sample
        registration + verification report

Usage:
    python 021_de_phase_points.py    (allocategnn env, any working directory)
"""

from __future__ import annotations

import os

# Thread caps must be set before numpy/scipy's first import (a GPU job is
# running a tau-parameter sweep elsewhere, so this script stays CPU-only,
# capped at 4 threads)
for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS",
           "OPENBLAS_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
    os.environ.setdefault(_v, "4")

import importlib.util
import json
import pickle
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

# Force UTF-8 console output on Windows (mirrors 019)
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# ---------------------------------------------------------------------------
# sys.path setup + loading the 019 module (correction-factor construction
# and Voronoi aggregation are reused directly from 019)
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
UK_EXP_DIR = PROJECT_ROOT / "StudyCase" / "British_weighter_experiments"
for _extra in (str(UK_EXP_DIR), str(PROJECT_ROOT)):
    if _extra not in sys.path:
        sys.path.insert(0, _extra)

from scipy.stats import pearsonr, spearmanr                             # noqa: E402


def _load_script_module(name: str, path: Path):
    """Load a script module whose filename starts with a digit via importlib (reuses 019's functions instead of reimplementing them)."""
    spec = importlib.util.spec_from_file_location(name, str(path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# 019 = the module defining the German base/factor/aggregation logic
# (loading it applies the scu.TARGET_CRS -> EPSG:25832 monkeypatch;
# compute_prox_scores reads the module-level global at call time)
de019 = _load_script_module("de019", SCRIPT_DIR / "019_de_additive_full_matrix.py")
scu = de019.scu                                    # the same scu module instance already patched by 019

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------
RESULTS_DIR = SCRIPT_DIR / "results"
STATIC_CSV = RESULTS_DIR / "static_allocation" / "boerde_static_metrics.csv"
MODELS_DIR = RESULTS_DIR / "models"
DE_MATRIX_CSV = RESULTS_DIR / "de_full_matrix.csv"

AU_EVAL_DIR = (PROJECT_ROOT / "StudyCase" / "Australia" / "data"
               / "processed" / "evaluation")
MERGED_IN_CSV = AU_EVAL_DIR / "uk_au_phase_points_merged.csv"   # read-only, not modified

POINTS_CSV = RESULTS_DIR / "de_phase_points.csv"
THREE_CSV = RESULTS_DIR / "three_country_phase_points.csv"
SUMMARY_JSON = RESULTS_DIR / "de_phase_summary.json"

SEEDS = [42, 123, 456]
SIGNALS = ["N", "P", "NP"]
CONFIG = "baseline"                 # GNN base = baseline config (same convention as 019)
EPS_RATIO = 1e-6                    # eps = total regional demand x EPS_RATIO (same protocol as the UK case)
DEMAND_COL = "p_mw"                 # German substation actual load column (same convention as 003/019)
COUNTRY = "DE"
LOCATION = "Boerde"                 # single region
N_STATIONS = 13

N_UK, N_AU = 240, 180
N_DE = 3 * (2 + len(SEEDS))         # 1 region x 3 signals x (2 static + 3 seeds) = 15

# Verification tolerances: 003/005 outputs are stored at 4 decimal places ->
# half a ulp (same as 019); 019's de_full_matrix is stored at full precision
# and is deterministic on the same CPU pipeline -> 1e-9
TOL_FROZEN_4DP = de019.TOL_FROZEN_4DP               # 5e-5 + 1e-9
TOL_FULLPREC = 1e-9

# Static arm labels: (base_type, signal) -> the 019 arm label (mirrors the Australia case's STATIC_ARM_MAP)
STATIC_ARM_MAP = {
    ("uniform", None): "Uni",
    ("uniform", "N"): "UniN", ("uniform", "P"): "UniP", ("uniform", "NP"): "UniNP",
    ("gpm", None): "GPM",
    ("gpm", "N"): "GPMpostN", ("gpm", "P"): "GPMpostP", ("gpm", "NP"): "GPMpostNP",
}
GNN_ARM_OF = {None: "GNN", "N": "GNNpostN", "P": "GNNpostP", "NP": "GNNpostNP"}

# The 18-column schema of the UK's empirical_points.csv (transcribed exactly
# from the Australia case; column set and order must not change)
UK_SCHEMA = [
    "base_type", "base_id", "seed", "fold", "location", "signal",
    "pearson_log", "spearman_log", "sigma_r", "sigma_c", "sigma_ratio",
    "rmse_base", "rmse_corrected", "delta_rmse",
    "theory_threshold", "predicted_help", "actual_help", "prediction_correct",
]

# Verdict thresholds (same rule as the UK case, generated programmatically rather than hand-entered)
VERDICT_TIERS = [(0.9, "supported"), (0.5, "partially_supported")]
VERDICT_RULE_TEXT = ("value >= 0.9 -> supported; value >= 0.5 -> "
                     "partially_supported; else not_supported")


def verdict_of(value: float) -> str:
    """Map a numeric value to a verdict label using a fixed rule (generated programmatically; same function as used for the UK case)."""
    for threshold, label in VERDICT_TIERS:
        if value >= threshold:
            return label
    return "not_supported"


# ---------------------------------------------------------------------------
# Alignment statistics (ported verbatim from the UK/Australia cases'
# alignment_stats function -- the definitions must match exactly)
# ---------------------------------------------------------------------------
def alignment_stats(d_true: np.ndarray, d_base: np.ndarray,
                    d_corr: np.ndarray, eps: float) -> dict:
    """Compute substation-level alignment statistics for one (base, signal) combination (same as the UK case).

    The ratio-based quantities are computed in log space; the difference
    quantities use raw values. eps is only used to protect the
    ratio/logarithm computation -- d_true - d_base in the difference
    convention uses the raw values.
    """
    d_true = np.asarray(d_true, dtype=float)
    d_base = np.asarray(d_base, dtype=float)
    d_corr = np.asarray(d_corr, dtype=float)
    n = len(d_true)
    assert n >= 3, f"Number of substations {n} < 3, cannot compute correlation"

    # eps-protection counts (number of samples that were <= 0 before protection)
    n_prot_true = int((d_true <= 0).sum())
    n_prot_base = int((d_base <= 0).sum())
    n_prot_corr = int((d_corr <= 0).sum())
    n_prot_any = int(((d_true <= 0) | (d_base <= 0) | (d_corr <= 0)).sum())

    # Ratio convention (log space)
    log_rho = np.log((d_true + eps) / (d_base + eps))
    log_f = np.log((d_corr + eps) / (d_base + eps))

    if np.std(log_f) == 0 or np.std(log_rho) == 0:
        raise RuntimeError("log F or log rho has zero variance -- the correlation coefficient is undefined, check this combination")

    pearson_log = float(pearsonr(log_f, log_rho)[0])
    spearman_log = float(spearmanr(log_f, log_rho)[0])

    # sigma_r / sigma_c (phase-diagram coordinates; population std, ddof=0, matching the UK case's convention)
    sigma_r = float(np.std(log_rho))
    sigma_c = float(np.std(log_f))

    return {
        "n_substations": n,
        "eps": float(eps),
        "n_eps_protected_true": n_prot_true,
        "n_eps_protected_base": n_prot_base,
        "n_eps_protected_corrected": n_prot_corr,
        "n_eps_protected_any": n_prot_any,
        "pearson_log": pearson_log,
        "spearman_log": spearman_log,
        "sigma_r": sigma_r,
        "sigma_c": sigma_c,
        "sigma_ratio": sigma_c / sigma_r,
    }


# ---------------------------------------------------------------------------
# Single-base analysis (a German-parameterized version of the Australia
# case's analyse_base function)
# ---------------------------------------------------------------------------
def analyse_base(ctx: dict, d_true: np.ndarray, eps: float,
                 base_demand: np.ndarray, base_type: str, base_id: str,
                 seed, fold) -> list:
    """Compute alignment statistics and delta RMSE for one base x three signals, returning a list of records."""
    grid_gdf = ctx["grid_gdf"]
    region_gdf = ctx["region_gdf"]
    subs_gdf = ctx["subs_gdf"]
    assignment = ctx["assignment"]

    subs_base = scu.aggregate_by_assignment(subs_gdf, assignment, base_demand)
    d_base = subs_base["allocated_demand"].values.astype(float)
    m_base = scu.evaluate_allocation(subs_base, actual_col=DEMAND_COL)

    rows = []
    for signal in SIGNALS:
        corrected = scu.apply_standard_multiplicative(
            base_demand, ctx["factors"][signal], grid_gdf, region_gdf)
        subs_corr = scu.aggregate_by_assignment(subs_gdf, assignment, corrected)
        d_corr = subs_corr["allocated_demand"].values.astype(float)
        m_corr = scu.evaluate_allocation(subs_corr, actual_col=DEMAND_COL)

        stats = alignment_stats(d_true, d_base, d_corr, eps)
        rows.append({
            "base_type": base_type,
            "base_id": base_id,
            "seed": seed,
            "fold": fold,
            "location": LOCATION,
            "signal": signal,
            **stats,
            "rmse_base": float(m_base["rmse"]),
            "rmse_corrected": float(m_corr["rmse"]),
            "delta_rmse": float(m_corr["rmse"] - m_base["rmse"]),
        })
    return rows


# ---------------------------------------------------------------------------
# Frozen-value verification checks (guard against drift in the base
# reconstruction; same approach as the Australia case, plus a dual anchor
# against 019)
# ---------------------------------------------------------------------------
def _check_anchor(dev: float, tol: float, what: str, anchor_log: list) -> None:
    """Record one verification check and raise if the deviation exceeds tolerance."""
    anchor_log.append({"what": what, "abs_dev": dev, "tol": tol,
                       "status": "ok" if dev <= tol else "FAIL"})
    if dev > tol:
        raise RuntimeError(f"Verification check failed: {what} deviation {dev:.3e} > tolerance {tol:.3e}")


_FROZEN_STATIC: pd.DataFrame | None = None
_SEED_METRICS: dict = {}
_MATRIX_RMSE: pd.DataFrame | None = None


def _static_frozen_value(arm: str) -> float:
    """Read the RMSE for an arm from 003's frozen boerde_static_metrics.csv (stored at 4 decimal places)."""
    global _FROZEN_STATIC
    if _FROZEN_STATIC is None:
        _FROZEN_STATIC = pd.read_csv(STATIC_CSV, index_col=0)
    return float(_FROZEN_STATIC.loc[de019.FROZEN_ROW_OF[arm], "rmse"])


def _gnn_frozen_value(arm: str, seed: int) -> float:
    """Read the RMSE for the voronoi_* row from 005's per-seed metrics.csv (stored at 4 decimal places)."""
    if seed not in _SEED_METRICS:
        path = MODELS_DIR / CONFIG / f"seed_{seed}" / "metrics.csv"
        _SEED_METRICS[seed] = pd.read_csv(path, index_col=0)
    return float(_SEED_METRICS[seed].loc[de019.SEED_ROW_OF[arm], "rmse"])


def _matrix_value(arm: str, seed: int | None = None) -> float:
    """Read the full-precision RMSE from 019's de_full_matrix.csv (seed=None retrieves the static arm's value)."""
    global _MATRIX_RMSE
    if _MATRIX_RMSE is None:
        df = pd.read_csv(DE_MATRIX_CSV, float_precision="round_trip")
        _MATRIX_RMSE = df[df["metric"] == "rmse"].set_index("arm")
    col = "value" if seed is None else f"value_seed_{seed}"
    return float(_MATRIX_RMSE.loc[arm, col])


def anchor_static(rows: list, anchor_log: list) -> None:
    """Static bases and all 6 multiplicative arms: dual-check against 003's frozen values (4dp) and 019's full-precision values."""
    by = {(r["base_type"], r["signal"]): r for r in rows
          if r["base_type"] in ("uniform", "gpm")}
    for bt in ("uniform", "gpm"):
        base_arm = STATIC_ARM_MAP[(bt, None)]
        got_base = by[(bt, "N")]["rmse_base"]
        _check_anchor(abs(got_base - _static_frozen_value(base_arm)),
                      TOL_FROZEN_4DP,
                      f"{bt} base vs 003 frozen {de019.FROZEN_ROW_OF[base_arm]}",
                      anchor_log)
        _check_anchor(abs(got_base - _matrix_value(base_arm)),
                      TOL_FULLPREC,
                      f"{bt} base vs 019 de_full_matrix {base_arm}", anchor_log)
        for sig in SIGNALS:
            arm = STATIC_ARM_MAP[(bt, sig)]
            got = by[(bt, sig)]["rmse_corrected"]
            _check_anchor(abs(got - _static_frozen_value(arm)),
                          TOL_FROZEN_4DP,
                          f"{bt}+{sig} vs 003 frozen {de019.FROZEN_ROW_OF[arm]}",
                          anchor_log)
            _check_anchor(abs(got - _matrix_value(arm)),
                          TOL_FULLPREC,
                          f"{bt}+{sig} vs 019 de_full_matrix {arm}", anchor_log)


def anchor_gnn(seed: int, rows: list, anchor_log: list) -> None:
    """GNN base + 3 multiplicative arms: dual-check against 005's per-seed values (4dp) and 019's full-precision values."""
    by = {r["signal"]: r for r in rows}
    got_base = by["N"]["rmse_base"]
    _check_anchor(abs(got_base - _gnn_frozen_value("GNN", seed)),
                  TOL_FROZEN_4DP,
                  f"gnn seed{seed} base vs 005 voronoi_GNN", anchor_log)
    _check_anchor(abs(got_base - _matrix_value("GNN", seed)),
                  TOL_FULLPREC,
                  f"gnn seed{seed} base vs 019 de_full_matrix GNN", anchor_log)
    for sig in SIGNALS:
        arm = GNN_ARM_OF[sig]
        got = by[sig]["rmse_corrected"]
        _check_anchor(abs(got - _gnn_frozen_value(arm, seed)),
                      TOL_FROZEN_4DP,
                      f"gnn seed{seed}+{sig} vs 005 {de019.SEED_ROW_OF[arm]}",
                      anchor_log)
        _check_anchor(abs(got - _matrix_value(arm, seed)),
                      TOL_FULLPREC,
                      f"gnn seed{seed}+{sig} vs 019 de_full_matrix {arm}",
                      anchor_log)


# ---------------------------------------------------------------------------
# Phase-diagram point table + confusion matrix (same approach as the UK/AU cases)
# ---------------------------------------------------------------------------
def build_phase_points(df: pd.DataFrame) -> pd.DataFrame:
    """Detail rows -> phase-diagram point table: coordinates + theoretical prediction + observed sign (same rule as the UK case)."""
    out = df.copy()
    out["theory_threshold"] = out["sigma_ratio"] / 2.0
    out["predicted_help"] = out["pearson_log"] > out["theory_threshold"]
    out["actual_help"] = out["delta_rmse"] < 0
    out["prediction_correct"] = out["predicted_help"] == out["actual_help"]
    return out[UK_SCHEMA + ["n_substations", "n_eps_protected_any"]]


def confusion_matrix_of(df: pd.DataFrame) -> dict:
    """2x2 confusion matrix (theoretical prediction x observed delta-RMSE sign; same function as the UK case)."""
    p = df["predicted_help"].values.astype(bool)
    a = df["actual_help"].values.astype(bool)
    cm = {
        "pred_help_actual_help": int((p & a).sum()),
        "pred_help_actual_hurt": int((p & ~a).sum()),
        "pred_hurt_actual_help": int((~p & a).sum()),
        "pred_hurt_actual_hurt": int((~p & ~a).sum()),
    }
    cm["total"] = int(sum(cm.values()))
    cm["accuracy"] = float((p == a).mean())
    return cm


def region_cell(df: pd.DataFrame) -> dict:
    """One summary cell: fraction of points on each side + median coordinates (generated by numeric rules; includes the hurt-side fraction)."""
    return {
        "n_rows": int(len(df)),
        "frac_predicted_help": float(df["predicted_help"].mean()),
        "frac_actual_help": float(df["actual_help"].mean()),
        "frac_predicted_hurt": float((~df["predicted_help"].astype(bool)).mean()),
        "frac_actual_hurt": float((~df["actual_help"].astype(bool)).mean()),
        "frac_prediction_correct": float(df["prediction_correct"].mean()),
        "median_pearson_log": float(df["pearson_log"].median()),
        "median_sigma_r": float(df["sigma_r"].median()),
        "median_sigma_c": float(df["sigma_c"].median()),
        "median_sigma_ratio": float(df["sigma_ratio"].median()),
        "median_delta_rmse": float(df["delta_rmse"].median()),
        "mean_delta_rmse": float(df["delta_rmse"].mean()),
    }


def fisher_ci95(rho: float, n: int) -> tuple[float, float]:
    """Approximate 95% CI for rho under the Fisher z transform (used for the small-sample registration; generated by numeric rules)."""
    z = float(np.arctanh(rho))
    se = 1.0 / np.sqrt(n - 3)
    return float(np.tanh(z - 1.96 * se)), float(np.tanh(z + 1.96 * se))


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------
def main() -> None:
    t0 = time.time()
    print("=" * 70)
    print("DE - phase-diagram points (021) -- 15 combinations x (rho, sigma_c/sigma_r) + three-country merged flagship data")
    print("=" * 70)

    # ── 0. Data loading (reuses the same functions defined in 019) ──
    grid_gdf, region_gdf, subs_gdf, ntl_values = de019.load_boerde()
    assert len(subs_gdf) == N_STATIONS, \
        f"Number of substations {len(subs_gdf)} != {N_STATIONS} -- ground-truth input has drifted"
    d_true = subs_gdf[DEMAND_COL].values.astype(float)
    region_total = float(np.asarray(region_gdf[de019.DERIVED_DEMAND_COL],
                                    dtype=float).sum())
    eps = region_total * EPS_RATIO
    print(f"Gemeinden: {grid_gdf['ITL3'].nunique()} | Substations: {N_STATIONS} | "
          f"Grid points: {len(grid_gdf)} | prox CRS: {scu.TARGET_CRS} | "
          f"eps = {eps:.6g}")

    # ── Factors and Voronoi assignment (frozen definitions from scu, via 019's implementation path) ──
    prox_scores = scu.compute_prox_scores(grid_gdf, subs_gdf)
    ntl_factor, prox_factor = scu.compute_factors(grid_gdf, ntl_values,
                                                  prox_scores)
    factors = {"N": ntl_factor, "P": prox_factor, "NP": ntl_factor * prox_factor}
    assignment = scu.compute_voronoi_assignment(grid_gdf, subs_gdf)

    ctx = {"grid_gdf": grid_gdf, "region_gdf": region_gdf,
           "subs_gdf": subs_gdf, "assignment": assignment, "factors": factors}

    records: list = []
    anchor_log: list = []

    # ── 1. Static bases (reuses the same functions defined in 019) ──
    uni_base = de019.compute_uniform_base(grid_gdf, region_gdf)
    gpm_base, n_fb = de019.compute_gpm_base(grid_gdf, region_gdf, subs_gdf)

    records += analyse_base(ctx, d_true, eps, uni_base,
                            "uniform", "uniform", "-", "-")
    records += analyse_base(ctx, d_true, eps, gpm_base,
                            "gpm", "gpm", "-", "-")
    anchor_static(records, anchor_log)
    print(f"Static bases complete (GPM fallback groups: {n_fb}) | "
          f"{len(anchor_log)} verification checks passed so far")

    # ── 2. GNN base (baseline config x 3 seeds; single region has no test fold, so fold='-') ──
    for seed in SEEDS:
        gd_path = (MODELS_DIR / CONFIG / f"seed_{seed}"
                   / "grid_demands" / "boerde_grid_demands.pickle")
        with open(gd_path, "rb") as fh:
            gd = pickle.load(fh)
        gnn_base = np.asarray(gd["gnn_demand"], dtype=float)
        assert len(gnn_base) == len(grid_gdf), \
            f"seed{seed}: grid_demands length does not match the number of grid points"

        gnn_rows = analyse_base(ctx, d_true, eps, gnn_base, "gnn",
                                f"gnn_seed{seed}", str(seed), "-")
        anchor_gnn(seed, gnn_rows, anchor_log)
        records += gnn_rows
        np_row = [r for r in gnn_rows if r["signal"] == "NP"][0]
        print(f"  gnn seed{seed}: rho(NP)={np_row['pearson_log']:.3f}, "
              f"sigma_ratio(NP)={np_row['sigma_ratio']:.3f}, "
              f"dRMSE(NP)={np_row['delta_rmse']:+.3f} | "
              f"{len(anchor_log)} verification checks passed so far")

    raw_df = pd.DataFrame(records)
    emp = build_phase_points(raw_df)

    # ── 3. Row-count check + write de_phase_points.csv (country + UK schema) ──
    expected = {"uniform": len(SIGNALS), "gpm": len(SIGNALS),
                "gnn": len(SEEDS) * len(SIGNALS)}
    expected["total"] = sum(expected.values())
    actual_counts = {bt: int((emp["base_type"] == bt).sum())
                     for bt in ("uniform", "gpm", "gnn")}
    actual_counts["total"] = int(len(emp))
    assert actual_counts == expected, \
        f"Row count mismatch: actual={actual_counts} vs expected={expected}"
    assert (emp["n_substations"] == N_STATIONS).all(), \
        "Some rows have n_substations != 13 -- ground-truth input has drifted"

    de_out = emp[UK_SCHEMA].copy()
    de_out.insert(0, "country", COUNTRY)
    de_out.to_csv(POINTS_CSV, index=False, encoding="utf-8-sig")
    print(f"\nde_phase_points.csv: {len(de_out)} rows (schema = country + "
          f"the same 18 columns as the UK case, column-aligned with the "
          f"merged data) -> {POINTS_CSV}")

    # ── 4. Three-country merge (UK+AU rows are transcribed without
    # recomputation; the original merged file is treated as read-only) ──
    merged_in = pd.read_csv(MERGED_IN_CSV, dtype={"seed": str, "fold": str},
                            float_precision="round_trip")
    assert list(merged_in.columns) == ["country"] + UK_SCHEMA, \
        "uk_au merged columns do not match the expected schema -- an upstream change needs review"
    assert len(merged_in) == N_UK + N_AU, \
        f"uk_au merged row count {len(merged_in)} != {N_UK + N_AU}"
    cc = merged_in["country"].value_counts()
    assert int(cc["UK"]) == N_UK and int(cc["AU"]) == N_AU, \
        f"uk_au merged country counts look wrong: {cc.to_dict()}"

    three = pd.concat([merged_in, de_out], ignore_index=True)
    three.to_csv(THREE_CSV, index=False, encoding="utf-8-sig")
    print(f"three_country_phase_points.csv: {len(three)} rows"
          f" (UK {N_UK} + AU {N_AU} + DE {len(de_out)}) -> {THREE_CSV}")

    # ── 5. Confusion matrix + placement verification (generated by numeric rules) ──
    cm_de = confusion_matrix_of(emp)
    cm_by_bt = {bt: confusion_matrix_of(emp[emp["base_type"] == bt])
                for bt in ("uniform", "gpm", "gnn")}

    gnn = emp[emp["base_type"] == "gnn"]
    gnn_np = gnn[gnn["signal"] == "NP"]
    static = emp[emp["base_type"].isin(["uniform", "gpm"])]

    # Core check 1: Germany's GNN x multiplicative combinations fall in the hurt region (German replication of the UK case's Proposition 2)
    de_gnn_hurt_value = float(min(
        (~gnn["predicted_help"].astype(bool)).mean(),
        (~gnn["actual_help"].astype(bool)).mean()))
    de_gnn_np_hurt_value = float(min(
        (~gnn_np["predicted_help"].astype(bool)).mean(),
        (~gnn_np["actual_help"].astype(bool)).mean()))
    # Core check 2: Germany's static x multiplicative combinations fall in the help region (German replication of the UK case's Proposition 1)
    de_static_help_value = float(min(static["predicted_help"].mean(),
                                     static["actual_help"].mean()))

    # Consistency of the observed worsening magnitude: 019 measured
    # GNNpostN +64% / GNNpostNP +193% (seed mean)
    worsening = {}
    for sig in SIGNALS:
        sub = gnn[gnn["signal"] == sig]
        rel_seed_mean = float(sub["rmse_corrected"].mean()
                              / sub["rmse_base"].mean() - 1.0)
        rel_from_019 = float(_matrix_value(GNN_ARM_OF[sig])
                             / _matrix_value("GNN") - 1.0)
        worsening[sig] = {
            "rel_change_seed_mean": rel_seed_mean,
            "rel_change_from_019_matrix": rel_from_019,
            "abs_dev_vs_019": abs(rel_seed_mean - rel_from_019),
            "frac_predicted_hurt": float(
                (~sub["predicted_help"].astype(bool)).mean()),
            "frac_actual_hurt": float(
                (~sub["actual_help"].astype(bool)).mean()),
            "theory_consistent_with_observed_worsening": bool(
                ((~sub["predicted_help"].astype(bool))
                 == (~sub["actual_help"].astype(bool))).all()),
        }

    # Three-country merged confusion matrix (UK/AU boolean columns are transcribed as-is; DE is computed in this step)
    cm_three = confusion_matrix_of(three)
    cm_by_country = {c: confusion_matrix_of(three[three["country"] == c])
                     for c in ("UK", "AU", "DE")}

    # Three points on the same theoretical line for GNN x NP across
    # countries (UK hurt / AU help / DE hurt, each reported as
    # min(predicted fraction, observed fraction))
    def _np_side(df: pd.DataFrame, side: str) -> float:
        sub = df[(df["base_type"] == "gnn") & (df["signal"] == "NP")]
        p = sub["predicted_help"].astype(bool)
        a = sub["actual_help"].astype(bool)
        if side == "help":
            return float(min(p.mean(), a.mean()))
        return float(min((~p).mean(), (~a).mean()))

    three_sides = {
        "uk_gnn_np_hurt_value": _np_side(three[three["country"] == "UK"], "hurt"),
        "au_gnn_np_help_value": _np_side(three[three["country"] == "AU"], "help"),
        "de_gnn_np_hurt_value": de_gnn_np_hurt_value,
    }
    three_sides_value = float(min(three_sides.values()))

    # eps-protection registration
    eps_prot = {
        "rule": f"eps = total regional demand x {EPS_RATIO}",
        "eps_value": float(eps),
        "region_total_demand": region_total,
        "total_protected_any": int(raw_df["n_eps_protected_any"].sum()),
        "rows_with_any_protection": int(
            (raw_df["n_eps_protected_any"] > 0).sum()),
        "by_base_type": {
            bt: {
                "protected_true": int(raw_df.loc[raw_df["base_type"] == bt,
                                                 "n_eps_protected_true"].sum()),
                "protected_base": int(raw_df.loc[raw_df["base_type"] == bt,
                                                 "n_eps_protected_base"].sum()),
                "protected_corrected": int(
                    raw_df.loc[raw_df["base_type"] == bt,
                               "n_eps_protected_corrected"].sum()),
                "protected_any": int(raw_df.loc[raw_df["base_type"] == bt,
                                                "n_eps_protected_any"].sum()),
            } for bt in ("uniform", "gpm", "gnn")
        },
    }

    # Small-sample registration (a case worth flagging explicitly; generated by numeric rules)
    de_gnn_np_median_rho = float(gnn_np["pearson_log"].median())
    ci_lo, ci_hi = fisher_ci95(de_gnn_np_median_rho, N_STATIONS)
    small_sample = {
        "n_substations": N_STATIONS,
        "n_regions": 1,
        "note": "Germany = a single region (Boerde), 13 substations -- each "
                "point's rho is estimated from a sample of 13 substations, "
                "so the sampling error is large; this is reported as-is, "
                "with no statistical inference performed (consistent with "
                "the paper's Germany section)",
        "pearson_dof": N_STATIONS - 2,
        "fisher_z_se": float(1.0 / np.sqrt(N_STATIONS - 3)),
        "fisher_z_ci95_halfwidth": float(1.96 / np.sqrt(N_STATIONS - 3)),
        "example_de_gnn_np_median_rho": de_gnn_np_median_rho,
        "example_de_gnn_np_median_rho_ci95": [ci_lo, ci_hi],
        "ci_rule": "Fisher z transform approximation: tanh(atanh(rho) +/- 1.96/sqrt(n-3))",
    }

    anchors_failed = [a for a in anchor_log if a["status"] != "ok"]
    devs_4dp = [a["abs_dev"] for a in anchor_log if a["tol"] == TOL_FROZEN_4DP]
    devs_full = [a["abs_dev"] for a in anchor_log if a["tol"] == TOL_FULLPREC]

    summary = {
        "meta": {
            "generated_by": "021_de_phase_points.py",
            "purpose": "DE phase-diagram points (15 combinations) completing the three-country flagship phase-diagram data",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "theory": "help <=> rho(r,c) > sigma_c/(2*sigma_r); coordinates = "
                      "substation-level (corr(log F, log rho_resid), "
                      "std(log F)/std(log rho_resid)) (same convention as "
                      "the UK and Australia cases)",
            "theory_line": "alpha* = sigma_ratio / 2",
            "prediction_rule": "predicted_help <=> pearson_log > sigma_ratio / 2",
            "actual_rule": "actual_help <=> delta_rmse < 0",
            "verdict_rule": VERDICT_RULE_TEXT,
            "inputs": [
                "results/models/baseline/seed_*/grid_demands/"
                "boerde_grid_demands.pickle (GNN base, read-only)",
                "results/static_allocation/boerde_static_metrics.csv"
                " (verification, read-only)",
                "results/models/baseline/seed_*/metrics.csv (verification, read-only)",
                "results/de_full_matrix.csv (full-precision pipeline verification, read-only)",
                str(MERGED_IN_CSV.relative_to(PROJECT_ROOT))
                + " (merge input, read-only, not modified)",
            ],
            "randomness": "This step has no source of randomness (deterministic post-processing)",
            "notes": [
                "Substation level only: agent (grid-point) level has no "
                "observed ground truth, so grid-point residuals are "
                "undefined (established for the UK case and equally true "
                "for Germany).",
                "The correction-factor construction and Voronoi aggregation "
                "reuse 019's implementation path directly (EPSG:25832 "
                "monkeypatch, 'Name' -> 'ITL3' alias, working_crs=3857), "
                "with zero change to the numerical semantics.",
                "Verdict fields (value/verdict) are always generated by "
                "numeric rules, never entered by hand.",
                "Delta RMSE is computed on the raw (not eps-protected) "
                "allocation values (actual_col='p_mw').",
            ],
            "deviations": [
                {"id": 1, "item": "Single region, single fold: the GNN base is the training region's own prediction",
                 "detail": "005 has no k-fold test fold (fold='-'), which "
                           "differs from the UK/AU test-fold convention -- "
                           "an in-sample base, reported as such"},
                {"id": 2, "item": "Demand convention = p_mw; regional demand is derived from substations",
                 "detail": "Regional 'Demand (MVA)' = substation p_mw summed "
                           "per Gemeinde (same formula as 003) -- d_true and "
                           "the total regional demand share the same source, "
                           "whereas UK/AU use independent statistical sources"},
                {"id": 3, "item": "CRS/alias adaptation reuses 019",
                 "detail": "EPSG:25832 monkeypatch + Voronoi "
                           "working_crs=3857 (the value used consistently "
                           "across 003/005/009/019)"},
                {"id": 4, "item": "n=13 substations, single region",
                 "detail": "rho's sample size is small (see "
                           "small_sample_registration); no statistical "
                           "inference is performed (consistent with the "
                           "paper's Germany section)"},
            ],
        },
        "n_stations": N_STATIONS,
        "small_sample_registration": small_sample,
        "row_counts": {"expected": expected, "actual": actual_counts},
        "eps_protection": eps_prot,
        "anchor_check": {
            "n_anchors": len(anchor_log),
            "n_failed": len(anchors_failed),
            "max_abs_dev_frozen_4dp_anchors": float(max(devs_4dp)),
            "frozen_4dp_tol": TOL_FROZEN_4DP,
            "max_abs_dev_fullprec_anchors": float(max(devs_full)),
            "fullprec_tol": TOL_FULLPREC,
            "tolerance_note": "003/005 outputs are stored at 4 decimal "
                              "places -> half a ulp of 5e-5 plus margin "
                              "(same as 019); 019's de_full_matrix is "
                              "stored at full precision and is "
                              "deterministic on the same CPU pipeline -> 1e-9",
            "all_passed": len(anchors_failed) == 0,
        },
        "confusion_matrix": cm_de,
        "confusion_by_base_type": cm_by_bt,
        "de_gnn_mult_in_hurt_region": {
            "description": "Core check: Germany's GNN x multiplicative "
                           "combinations (all signals) fall in the "
                           "theoretical hurt region and worsen in practice "
                           "(German replication of the UK case's Proposition 2)",
            **region_cell(gnn),
            "value": de_gnn_hurt_value,
            "value_rule": "value = min(frac_predicted_hurt, frac_actual_hurt)",
            "verdict": verdict_of(de_gnn_hurt_value),
            "by_signal": {sig: region_cell(gnn[gnn["signal"] == sig])
                          for sig in SIGNALS},
        },
        "de_gnn_np_in_hurt_region": {
            "description": "The single GNN x NP arm (the one corresponding "
                           "to the paper's +193% worsening) falls in the "
                           "hurt region",
            **region_cell(gnn_np),
            "value": de_gnn_np_hurt_value,
            "value_rule": "value = min(frac_predicted_hurt, frac_actual_hurt)",
            "verdict": verdict_of(de_gnn_np_hurt_value),
        },
        "de_static_in_help_region": {
            "description": "Static arms (uniform+gpm) fall in the help "
                           "region (German replication of the UK case's Proposition 1)",
            **region_cell(static),
            "value": de_static_help_value,
            "value_rule": "value = min(frac_predicted_help, frac_actual_help)",
            "verdict": verdict_of(de_static_help_value),
        },
        "observed_worsening_consistency": {
            "description": "Registration of the consistency between the "
                           "theoretical prediction and 019's measured "
                           "worsening magnitude (GNNpostN +64% / "
                           "GNNpostNP +193%, seed mean)",
            "rel_change_rule": "rel = mean_seed(RMSE_corr) / "
                               "mean_seed(RMSE_base) - 1",
            "by_signal": worsening,
        },
        "three_country": {
            "note": "The UK/AU boolean columns are transcribed as-is from "
                    "uk_au_phase_points_merged.csv (read-only, not "
                    "modified); DE is computed in this step",
            "confusion_matrix_total": cm_three,
            "confusion_by_country": cm_by_country,
            "total_accuracy": cm_three["accuracy"],
            "gnn_np_three_sides": {
                "description": "Three points on the same theoretical line: "
                               "UK hurt AND AU help AND DE hurt (each "
                               "reported as min(predicted fraction, "
                               "observed fraction))",
                **three_sides,
                "value": three_sides_value,
                "value_rule": "value = min(uk_hurt, au_help, de_hurt)",
                "verdict": verdict_of(three_sides_value),
            },
        },
        "merged_output": {
            "file": THREE_CSV.name,
            "n_uk": N_UK, "n_au": N_AU, "n_de": int(len(de_out)),
            "n_total": int(len(three)),
            "note": "The paper's complete flagship phase-diagram data "
                    "(all three countries); the original "
                    "uk_au_phase_points_merged.csv is read-only and not modified",
        },
    }
    SUMMARY_JSON.write_text(json.dumps(summary, ensure_ascii=False, indent=1),
                            encoding="utf-8")
    print(f"de_phase_summary.json -> {SUMMARY_JSON}")

    # ── 6. Console summary ──
    print("\n" + "═" * 70)
    print("Key readouts (see de_phase_summary.json for the full report)")
    print("═" * 70)
    print(f"{len(anchor_log)} verification checks passed | max 4dp frozen "
          f"deviation {max(devs_4dp):.3e} | max full-precision pipeline "
          f"deviation {max(devs_full):.3e}")
    print(f"eps-protected samples: {eps_prot['total_protected_any']}"
          f" (affecting {eps_prot['rows_with_any_protection']} rows) | "
          f"n = {N_STATIONS} substations (Fisher z SE ~= "
          f"{small_sample['fisher_z_se']:.3f})")
    print(f"DE confusion matrix: help/help={cm_de['pred_help_actual_help']}, "
          f"help/hurt={cm_de['pred_help_actual_hurt']}, "
          f"hurt/help={cm_de['pred_hurt_actual_help']}, "
          f"hurt/hurt={cm_de['pred_hurt_actual_hurt']} "
          f"(total {cm_de['total']}, accuracy {cm_de['accuracy']:.3f})")
    g = summary["de_gnn_mult_in_hurt_region"]
    print(f"DE GNN x multiplicative (all signals, {g['n_rows']} rows): "
          f"predicted hurt {g['frac_predicted_hurt']:.3f} / actual hurt "
          f"{g['frac_actual_hurt']:.3f} -> value={g['value']:.3f} "
          f"[{g['verdict']}]")
    print(f"  Typical coordinates: median (rho, sigma_c/sigma_r) = "
          f"({g['median_pearson_log']:.3f}, "
          f"{g['median_sigma_ratio']:.3f}), threshold sigma_ratio/2 = "
          f"{g['median_sigma_ratio'] / 2:.3f}")
    s = summary["de_static_in_help_region"]
    print(f"DE static x multiplicative ({s['n_rows']} rows): predicted "
          f"help {s['frac_predicted_help']:.3f} / actual help "
          f"{s['frac_actual_help']:.3f} -> value={s['value']:.3f} "
          f"[{s['verdict']}]")
    for sig in SIGNALS:
        w = worsening[sig]
        print(f"  GNNpost{sig}: measured {w['rel_change_seed_mean']:+.1%} "
              f"vs 019 {w['rel_change_from_019_matrix']:+.1%} | "
              f"theory-observation agreement = "
              f"{w['theory_consistent_with_observed_worsening']}")
    tc = summary["three_country"]
    ts = tc["gnn_np_three_sides"]
    print(f"Three-country merged accuracy: {tc['total_accuracy']:.3f} (UK "
          f"{cm_by_country['UK']['accuracy']:.3f} / AU "
          f"{cm_by_country['AU']['accuracy']:.3f} / DE "
          f"{cm_by_country['DE']['accuracy']:.3f})")
    print(f"Three points: UK hurt {ts['uk_gnn_np_hurt_value']:.3f} AND AU "
          f"help {ts['au_gnn_np_help_value']:.3f} AND DE hurt "
          f"{ts['de_gnn_np_hurt_value']:.3f} -> value={ts['value']:.3f} "
          f"[{ts['verdict']}]")
    print(f"\nOutput directory: {RESULTS_DIR}")
    print(f"021 complete, elapsed {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
